webapp/views.py
import io
import os
import re
import shutil
import time
import zipfile

from flask import (
    Blueprint, flash, redirect, render_template, request, url_for, current_app as app, send_file
)
from werkzeug.utils import secure_filename

from . import preprocess, predict, executor, task_meta_data

bp = Blueprint('views', __name__)


@bp.route("/")
def index():
    return render_template('index.html.j2')


@bp.route("/predict", methods=['GET'])
def view_predict():
    return render_template('predict.html.j2')


@bp.route("/predict", methods=['POST'])
def submit_predict():
    errors = False
    error_msg = ""
    # get parameters from form
    sc = request.form['sc']
    fs = request.form['fs']
    model = request.form['model']
    method = int(request.form['method'])
    cutoff = float(request.form['cutoff'])
    user = request.form['user']

    # save files in new directory name based on user and microtime
    micro_time = time.time_ns() // 1000000
    work_folder = f"prediction_{user}_{micro_time}"
    work_dir = os.path.join(app.instance_path, work_folder)
    in_dir = os.path.join(work_dir, 'input')
    out_dir = os.path.join(work_dir, 'output')
    os.makedirs(work_dir)
    os.makedirs(in_dir)
    os.makedirs(out_dir)

    if not errors and 'chrname' in request.files:
        chrfile = request.files['chrname']
        chrfileFilename = secure_filename(chrfile.filename)
        chrfile.save(os.path.join(in_dir, chrfileFilename))
    else:
        errors = True
        error_msg = "Metadata CSV required"

    if not errors and 'inputname' in request.files:
        infile = request.files['inputname']
        infileFilename = secure_filename(infile.filename)
        infile.save(os.path.join(in_dir, infileFilename))
    else:
        errors = True
        error_msg = "Medicare Claims file required"

    if not errors:
        # save run info and pass info off to prediction function
        task_meta_data[work_folder] = {}
        task_meta_data[work_folder]['start_time'] = time.strftime('%m/%d/%Y %H:%M:%S')
        task_meta_data[work_folder]['run_options'] = {
            'feature_set': fs,
            'model': model,
            'cutoff': cutoff
        }
        executor.submit_stored(work_folder, predict.predict, fs, sc, model, infileFilename, chrfileFilename, cutoff,
                               method,
                               out_dir, in_dir)
        flash(f"Prediction task {work_folder} started.")
        return redirect(url_for('views.view_tasks'))
    else:
        flash(error_msg)
    return render_template('predict.html.j2')


@bp.route("/preprocess", methods=['GET'])
def view_preprocess():
    return render_template('preprocess.html.j2')


@bp.route("/preprocess", methods=['POST'])
def submit_preprocess():
    errors = False
    error_msg = ""
    # get parameters from form
    user = request.form['user']
    num_data = request.form['numdata']

    if 'mld' in request.form and request.form['mld'] is not None and request.form['mld'] != '':
        month_len_medicaid = int(request.form['mld'])
    else:
        month_len_medicaid = 0

    if 'mle' in request.form and request.form['mle'] is not None and request.form['mle'] != '':
        month_len_medicare = int(request.form['mle'])
    else:
        month_len_medicare = 0

    if 'sd' in request.form:
        start_medicaid = request.form['sd']
    else: 
        start_medicaid = 0

    if 'se' in request.form: 
        start_medicare = request.form['se']
    else:
        start_medicare = 0
    drug_code = request.form['dc']

    # save files in new directory name based on user and microtime
    user = re.sub(r'\s+', '_', user)
    user = re.sub(os.path.sep, '_', user)
    micro_time = time.time_ns() // 1000000
    job_name = f"preprocess_{user}_{micro_time}"
    work_dir = os.path.join(app.instance_path, job_name)
    in_dir = os.path.join(work_dir, 'input')
    out_dir = os.path.join(work_dir, 'output')
    os.makedirs(work_dir)
    os.makedirs(in_dir)
    os.makedirs(out_dir)
    metacsvFilename = None
    mecareClaimsFilename = None
    mecareEnrollFilename = None
    mecaidClaimsFilename = None
    mecaidClaims2Filename = None
    mecaidEnrollFilename = None

    if not errors and 'metacsv' in request.files and request.files['metacsv'].filename != '':
        metacsv = request.files['metacsv']
        metacsvFilename = secure_filename(metacsv.filename)
        metacsv.save(os.path.join(in_dir, metacsvFilename))
    else:
        errors = True
        error_msg = "Incidence Metadata CSV required"

    if num_data == "0" or num_data == "1":
        if not errors and 'mecareClaims' in request.files and request.files['mecareClaims'].filename != '':
            mecareClaims = request.files['mecareClaims']
            mecareClaimsFilename = secure_filename(mecareClaims.filename)
            mecareClaims.save(os.path.join(in_dir, mecareClaimsFilename))
        else:
            errors = True
            error_msg = "Medicare Claims file required"

        if not errors and 'mecareEnroll' in request.files and request.files['mecareEnroll'].filename != '':
            mecareEnroll = request.files['mecareEnroll']
            mecareEnrollFilename = secure_filename(mecareEnroll.filename)
            mecareEnroll.save(os.path.join(in_dir, mecareEnrollFilename))
        else:
            errors = True
            error_msg = "Medicare Enrollment file required"

    if num_data == "0" or num_data == "2":
        if not errors and 'mecaidClaims' in request.files and request.files['mecaidClaims'].filename != '':
            mecaidClaims = request.files['mecaidClaims']
            mecaidClaimsFilename = secure_filename(mecaidClaims.filename)
            mecaidClaims.save(os.path.join(in_dir, mecaidClaimsFilename))
        else:
            errors = True
            error_msg = "Medicaid/Other Claims file required"

        if not errors and 'mecaidClaims2' in request.files and request.files['mecaidClaims2'].filename != '':
            mecaidClaims2 = request.files['mecaidClaims2']
            mecaidClaims2Filename = secure_filename(mecaidClaims2.filename)
            mecaidClaims2.save(os.path.join(in_dir, mecaidClaims2Filename))
        else:
            errors = True
            error_msg = "Medicaid/Other Pharmacy Claims file required"

        if not errors and 'mecaidEnroll' in request.files and request.files['mecaidEnroll'].filename != '':
            mecaidEnroll = request.files['mecaidEnroll']
            mecaidEnrollFilename = secure_filename(mecaidEnroll.filename)
            mecaidEnroll.save(os.path.join(in_dir, mecaidEnrollFilename))
        else:
            errors = True
            error_msg = "Medicaid/Other Enrollment file required"

    # pass info off to executor
    if not errors:
        executor.submit_stored(job_name, preprocess.preprocess_data,
                               user, num_data, in_dir, out_dir, metacsvFilename, mecareClaimsFilename,
                               mecareEnrollFilename,
                               mecaidClaimsFilename, mecaidClaims2Filename, mecaidEnrollFilename, month_len_medicaid,
                               month_len_medicare,
                               start_medicaid, start_medicare, drug_code)
        flash(f"Task {job_name} started")
        task_meta_data[job_name] = {}
        task_meta_data[job_name]['start_time'] = time.strftime('%m/%d/%Y %H:%M:%S')
        task_meta_data[job_name]['run_options'] = {
            'num_data': num_data,
            'mon_len_medicaid': month_len_medicaid,
            'mon_len_medicare': month_len_medicare,
            'start_medicaid': start_medicaid,
            'start_medicare': start_medicare,
            'drug_code': drug_code
        }
        return redirect(url_for('views.view_tasks'))
    else:
        flash(error_msg)
    return render_template('preprocess.html.j2')


@bp.route('/tasks')
def view_tasks():
    task_status = []
    for task_name in executor.futures._futures.keys():
        ts = {}
        ts['task_name'] = task_name
        ts['task_status'] = executor.futures._futures[task_name]._state
        if ts['task_status'] == 'FINISHED' and executor.futures._futures[task_name].exception() is not None:
            ts['task_message'] = executor.futures._futures[task_name].exception()
            ts['task_status'] = 'ERROR'
        else:
            if task_name in task_meta_data and 'start_time' in task_meta_data[task_name]:
                ts['task_message'] = task_meta_data[task_name]['start_time']
        task_status.append(ts)
    return render_template('tasks.html.j2', task_status=task_status)


@bp.route('/tasks/<string:task_name>/download')
def download_task(task_name: str):
    # work dir shouldn't contain slashes because of the flask string converter, but just in case sanitize the path to
    # prevent escape. it will remove the passed directory tree at the end of this so best to be extra safe...
    work_dir = os.path.relpath(os.path.normpath(os.path.join("/", task_name)), "/")
    work_dir = os.path.join(app.instance_path, work_dir)
    out_dir = os.path.join(work_dir, "output")

    # zip up output files - out_dir/*.csv
    files = []
    if task_name.startswith('preprocess'):
        for dirpath, dirnames, filenames in os.walk(out_dir):
            for file in filenames:
                if file.startswith('All_11E_') or file.startswith('8_PatientLevel_char_'):
                    files.append(os.path.join(dirpath, file))
    if task_name.startswith('prediction'):
        files = list(filter(lambda x: x.endswith('.csv'), os.listdir(out_dir)))

    file_obj = io.BytesIO()
    with zipfile.ZipFile(file_obj, 'w') as zip_file_handle:
        for file in files:

webapp/templates/base.html.j2
<!doctype html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %} - RECAPSE</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
  <nav>
    <h1><a href="{{ url_for('views.index') }}">RECAPSE Recurrence Prediction</a></h1>
    <ul>
        <li><a href="{{ url_for('views.view_tasks') }}">Running/Completed Tasks</a>
        <li><a href="{{ url_for('views.view_preprocess') }}">Preprocess Data</a>
        <li><a href="{{ url_for('views.view_predict') }}">Run Prediction</a>
    </ul>
  </nav>
  <section class="content">
    <header>
    {% block header %}{% endblock %}
    </header>
    {% for message in get_flashed_messages() %}
      <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
  </section>
</body>
</html>

webapp/templates/index.html.j2
{% extends 'base.html.j2' %}

{% block header %}
    <h1>{% block title %}Main{% endblock %}</h1>
{% endblock %}

{% block content %}
    <h2>User Guide</h2>
    <p>Recurrence using Claims and PROs for SEER Expansion (RECAPSE) is an XGBoost model for predicting second breast
        cancer events (recurrence and new breast primary) based on registry cancer incidence data linked with insurance
        enrollment and claims data.</p>
    <p>The purpose of this tool is to provide prediction of second breast cancer events and improve the efficiency of
        registry operation effort to identify recurrences. Registries can utilize the results to manually check these
        cases for true recurrences. Users can adjust the cut-off value to control the sensitivity and specificity of
        the results based on their own specific data and resources available.</p>
    <h2>Preprocessing Data</h2>
    <p>The first step is to preprocess the data. This is a time-consuming step that generates two files needed for the
        prediction step:
        <ol>
            <li>Incidence File: Contains consolidated patient-level data.</li>
            <li>Feature File: Contains all the features used as input into the XGBoost prediction.</li>
        </ol>
    After the preprocessed data is generated, the two files can be fed through the model to generate predictions.</p>
    <p>For details on creating the input files and the features required in the input data, see:</p>
    <ul>
        <li><a href="{{ url_for('static', filename='recapse_data_processing_guide.docx') }}">Data processing guide</a></li>
        <li><a href="{{ url_for('static', filename='recapse_input_columns_needed.xlsx') }}">Input data dictionary</a></li>
    </ul>
    <p>Preprocessing options</p>
    <ul>
        <li>Job Name - A string that will be put in the automatically generated task ID to help you identify the task</li>
        <li>Data Type - Medicaid/Other only, Medicare only, or both</li>
        <li>Length of medicaid/other enrollment file in months (not needed for medicare only)</li>
        <li>Start date of medicaid/other enrollment (not needed for medicare only)</li>
        <li>Length of medicare enrollment file in months (not needed for medicaid/other only)</li>
        <li>Start date of medicare enrollment (not needed for medicare/other only)</li>
        <li>Drug Codes - Defines which drugs in claims data are processed to define generated features. Looks for either
            Maytansinoid DM3 drugs or valproic acid and related drugs found by a short GNN model.</li>
    </ul>
    <p>Files needed for preprocessing</p>
    <ul>
        <li>Registry Incidence file</li>
        <li>Enrollment file (both Medicare and Medicaid/Other)</li>
        <li>Claims file (both Medicare and Medicaid/Other)</li>
        <li>Pharmacy claims file (Medicaid/Other only)</li>
    </ul>
    <p>Prediction options</p>
    <ul>
        <li>Job Name - A string that will be put in the automatically generated task ID to help you identify the task</li>
        <li>Input feature sets - Should match the drug codes used to preprocess the files being submitted. If preprocessed
            using short GNN drug grouped features, the default file name will contain "CCSandVAL2nd". If using DM3
            specific drug features, the default filename from preprocessing will contain "CCSandDM3SPE".</li>
        <li>SBCE Definition - Include or exclude death related to the first primary as a Second Breast Cancer Event (SBCE)</li>
        <li>Model Type - Select the full model or limit to a smaller model using only the top features for prediction</li>
        <li>Prediction Output Detail Level - Level of detail of output. The month level output contains a row for each patient for each month. This file can get very large.</li>
        <li>Cutoff - The prediction score above which a recurrence signal is detected.</li>
    </ul>
{% endblock %}

webapp/templates/predict.html.j2
{% extends 'base.html.j2' %}

{% block header %}
  <h1>{% block title %}Prediction{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post" action="{{ url_for("views.submit_predict") }}" enctype="multipart/form-data">
    <h2>Prediction options</h2>
    <label for="user">Job Name:</label>
    <input name="user" id="user" required />
    <label for="inputname">Model Input Features (from Preprocessing 11E output):</label>
    <input name="inputname" id="inputname" type="file" accept=".pkl" />
    <label for="chrname">Patient level characteristics XLSX (from step 8 output):</label>
    <input name="chrname" id="chrname" type="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" />
    <label for="fs">Input Feature Sets:</label>
    <select name="fs" id="fs">
      <option value="CCSandVAL2nd">Short GNN drug grouped features (file name contains CCSandVAL2nd)</option>
      <option value="CCSandDM3SPE">DM3 specific drug (file name contains CCSandDM3SPE)</option>
    </select>
    <label for="sc">SBCE Definition:</label>
    <select name="sc" id="sc">
      <option value="SBCE">Include death related to first primary</option>
      <option value="SBCE_Excluded_DeathPts">Exclude death related to first primary</option>
    </select>
    <label for="model">Model:</label>
    <select name="model" id="model">
        <option value="Full_Model">Full Model</option>
      <option value="TopF_Model">Top Features Model</option>
    </select>
    <label for="method">Prediction Output Detail Level:</label>
    <select name="method" id="method">
      <option value="1">Only patient-level prediction</option>
{#      <option value="2">Only month-level prediction (warning: generates a large file)</option>#}
      <option value="0">Both patient-level and month-level prediction</option>
    </select>
    <label for="cutoff">Cutoff (0.1-0.9):</label>
    <input name="cutoff" id="cutoff" type="number" min="0.1" max="0.9" step="0.1" value="0.5"/>
    <input type="submit" value="Upload for Prediction" />
  </form>
{% endblock %}

webapp/templates/predict_result.html.j2
{% extends 'base.html.j2' %}

{% block header %}
    <h1>{% block title %}Prediction{% endblock %}</h1>
{% endblock %}

{% block content %}
    <h2>Prediction Results for {{ task_name }}</h2>
    <p>Here are summary statistics from the prediction run.</p>
    <p><strong>Number of patients:</strong> {{ results['count'] }}</p>
    <p><strong>Prediction model:</strong> {{ run_options['model'] }}</p>
    <p><strong>Features used:</strong> {{ run_options['feature_set'] }}</p>
    <p><strong>Cutoff:</strong> {{ run_options['cutoff'] }}</p>
    <p><strong>Number of recurrences predicted:</strong> {{ results['recurrences'] }}</p>
    <h3>By Race</h3>
    <table>
        <tr>
            <th>&nbsp;</th><th>Total</th><th>Recurrences</th>
        </tr>
        {% for key in results['by_race'] %}
        <tr>
            <th>{{ key }}</th><td>{{ results['by_race'][key][0] }}</td><td>{{ results['by_race'][key][1] }}</td>
        </tr>
        {% endfor %}
    </table>
    <h3>By Stage</h3>
    <table>
        <tr>
            <th>&nbsp;</th><th>Total</th><th>Recurrences</th>
        </tr>
        {% for key in results['by_stage'] %}
        <tr>
            <th>{{ key }}</th><td>{{ results['by_stage'][key][0] }}</td><td>{{ results['by_stage'][key][1] }}</td>
        </tr>
        {% endfor %}
    </table>
    <h3>By Diagnosis Year</h3>
    <table>
        <tr>
            <th>&nbsp;</th><th>Total</th><th>Recurrences</th>
        </tr>
        {% for key in results['by_year'] %}
        <tr>
            <th>{{ key }}</th><td>{{ results['by_year'][key][0] }}</td><td>{{ results['by_year'][key][1] }}</td>
        </tr>
        {% endfor %}
    </table>
    <h3>By Age at Diagnosis</h3>
    <table>
        <tr>
            <th>&nbsp;</th><th>Total</th><th>Recurrences</th>
        </tr>
        {% for key in results['by_age'] %}
            <tr>
                <th>{{ key }}</th><td>{{ results['by_age'][key][0] }}</td><td>{{ results['by_age'][key][1] }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

webapp/templates/preprocess.html.j2
{% extends 'base.html.j2' %}

{% block header %}
    <h1>{% block title %}Preprocessing{% endblock %}</h1>
    <script>
    function updateFieldsOnDataTypeChange(f) {
        const medicareFields = document.getElementsByClassName("medicare");
        const medicaidFields = document.getElementsByClassName("medicaid");
        if (f.value === "0") { // both
            for(let i=0; i<medicareFields.length; i++) {
                if (medicareFields[i].disabled !== undefined) medicareFields[i].disabled = false;
            }
            for(let i=0; i<medicaidFields.length; i++) {
                if (medicaidFields[i].disabled !== undefined) medicaidFields[i].disabled = false;
            }
        }
        else if (f.value === "1") { // medicare only
            for(let i=0; i<medicareFields.length; i++) {
                if (medicareFields[i].disabled !== undefined) medicareFields[i].disabled = false;
            }
            for(let i=0; i<medicaidFields.length; i++) {
                if (medicaidFields[i].disabled !== undefined) medicaidFields[i].disabled = true;
            }
        }
        else if (f.value === "2") { // medicaid/other only
            for (let i = 0; i < medicareFields.length; i++) {
                if (medicareFields[i].disabled !== undefined) medicareFields[i].disabled = true;
            }
            for (let i = 0; i < medicaidFields.length; i++) {
                if (medicaidFields[i].disabled !== undefined) medicaidFields[i].disabled = false;
            }
        }
    }
    </script>
{% endblock %}

{% block content %}
  <form method="post" action="{{ url_for("views.submit_preprocess") }}" enctype="multipart/form-data">
    <h2>Preprocessing options</h2>
    <label for="user">Job Name:</label>
    <input name="user" id="user" required />
    <label for="numdata">Data Type:</label>
    <select name="numdata" id="numdata" onload="updateFieldsOnDataTypeChange(this)" onchange="updateFieldsOnDataTypeChange(this);">
      <option value="0">Both</option>
      <option value="1">Only Medicare</option>
      <option value="2">Only Medicaid or Other Claims</option>
    </select>
    <label for="mld" class="medicaid">Length of Medicaid or Other Insurance Enrollment File (in months):</label>
    <input name="mld" id="mld" class="medicaid" />
    <label for="sd" class="medicaid">Start Date for Medicaid/Other Enrollment (YYYY-MM-DD):</label>
    <input name="sd" id="sd" class="medicaid" />
    <label for="mle" class="medicare">Length of Medicare Enrollment File (in months):</label>
    <input name="mle" id="mle" class="medicare" />
    <label for="se" class="medicare">Start Date for Medicare Enrollment (YYYY-MM-DD):</label>
    <input name="se" id="se" class="medicare" />
    <label for="dc">Drug Code:</label>
    <select name="dc" id="dc">
      <option value="VAL_2ND">Short GNN drug grouped features</option>
      <option value="DM3_SPE">DM3 specific drug</option>
    </select>
    <label for="metacsv">Registry Incidence Data CSV:</label>
    <input name="metacsv" id="metacsv" type="file" accept="text/csv" />
    <label for="mecaidClaims" class="medicaid">Medicaid/Other Claims CSV:</label>
    <input name="mecaidClaims" id="mecaidClaims" type="file" accept="text/csv" class="medicaid" />
    <label for="mecaidlaims2" class="medicaid">Medicaid/Other Pharmacy Claims CSV:</label>
    <input name="mecaidClaims2" id="mecaidlaims2" type="file" accept="text/csv" class="medicaid" />
    <label for="mecaidEnroll" class="medicaid">Medicaid/Other Enrollment CSV:</label>
    <input name="mecaidEnroll" id="mecaidEnroll" type="file" accept="text/csv" class="medicaid" />
    <label for="mecareClaims" class="medicare">Medicare Claims CSV:</label>
    <input name="mecareClaims" id="mecareClaims" type="file" accept="text/csv" class="medicare" />
    <label for="mecareEnroll" class="medicare">Medicare Enrollment CSV:</label>
    <input name="mecareEnroll" id="mecareEnroll" type="file" accept="text/csv" class="medicare" />
    <input type="submit" value="Upload for Preprocessing" />
  </form>
  <script>
    // call the update function once the page is loaded to make sure the input state matches the form state
    (function () {
        updateFieldsOnDataTypeChange(document.getElementById("numdata"));
    })();
  </script>
{% endblock %}

webapp/templates/preprocess_result.html.j2
{% extends 'base.html.j2' %}

{% block header %}
    <h1>{% block title %}Prediction{% endblock %}</h1>
{% endblock %}

{% block content %}
    <h2>Preprocessing Results for {{ task_name }}</h2>
    <p>Here is some information about this preprocessing job.</p>
    <p><strong>Number of patients:</strong> {{ results['num_patients'] }}</p>
    <p><strong>Number of patient-months:</strong> {{ results['num_patient_months'] }}</p>
    <p><strong>Number of features:</strong> {{ results['num_features'] }}</p>
    {% if run_options['num_data'] == "0" %}
    <p><strong>Data type: </strong>Both Medicare and Medicaid/Other Insurance</p>
    <p><strong>Medicare Data: </strong>From {{ run_options['start_medicare'] }}, Length {{ run_options['mon_len_medicare'] }} months</p>
    <p><strong>Medicaid/Other Insurance Data: </strong>From {{ run_options['start_medicaid'] }}, Length {{ run_options['mon_len_medicaid'] }} months</p>
    {% elif run_options['num_data'] == "1" %}
    <p><strong>Data type: </strong>Medicare Only</p>
    <p>From {{ run_options['start_medicare'] }}, Length {{ run_options['mon_len_medicare'] }} months</p>
    {% elif run_options['num_data'] == "2" %}
    <p><strong>Data type: </strong>Medicaid/Other Insurance Only</p>
    <p>From {{ run_options['start_medicaid'] }}, Length {{ run_options['mon_len_medicaid'] }} months</p>
    {% endif %}
    {% if run_options['drug_code'] == "VAL_2ND" %}
    <p><strong>Drug Features: </strong>Short GNN drug grouped features</p>
    {% elif run_options['drug_code'] == "DM3_SPE" %}
    <p><strong>Drug Features: </strong>DM3 Specific Drug</p>
    {% endif %}
{% endblock %}

webapp/templates/tasks.html.j2
{% extends 'base.html.j2' %}

{% block header %}
    <h1>{% block title %}Tasks{% endblock %}</h1>
{% endblock %}

{% block content %}
    <h2>All Tasks</h2>
    <table style="width: 100%;">
        <tr>
            <th>Task ID</th><th>State</th><th>Info</th><th>Actions</th>
        </tr>
        {% for ts in task_status %}
            <tr>
                <th>{{ ts['task_name'] }}</th>
                <td>{{ ts['task_status'] }}</td>
                <td>
                    {% if ts['task_status'] == 'FINISHED' %}
                    Task finished successfully.
                    {% elif ts['task_status'] == 'ERROR' %}
                    {{ ts['task_message'] }}
                    {% else %}
                    Started at {{ ts['task_message'] }}
                    {% endif %}
                </td>
                <td>
                    {% if ts['task_status'] == 'FINISHED' %}
{#                        {% if ts['task_name'].startswith('prediction') %}#}
                        <a href="{{ url_for("views.view_task_result", task_name=ts['task_name']) }}">Results Summary</a>
{#                        {% endif %}#}
                    <a href="{{ url_for("views.download_task", task_name=ts['task_name']) }}">Download Files</a>
                    <a href="{{ url_for("views.remove_task", task_name=ts['task_name']) }}">Remove</a>
                    {% elif ts['task_status'] == 'ERROR' %}
                    {{ ts['task_message'] }}
                    {% else %}
                    &nbsp;
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}